### ISSUE TITLE
buildkite-cloudwatch-metrics-publisher deployment JSON only works in us-east-1

### ISSUE THREAD

**Issue by npaufler** [buildkite/buildkite-cloudwatch-metrics-publisher#10]
Because the lambda files referenced in the JSON are in the S3 bucket buildkite-cloudwatch-metrics-publisher (which is in us-east-1), trying to deploy the stack in any other region will fail.

Lambda requires that the S3 bucket it accesses for deployment be in the same region.

I'm not sure if there is any real fix other than to have multiple JSON files referencing different S3 buckets containing the ZIPs, one for each region. 

To confirm this does work I tested by creating a new S3 bucket in us-west-2 and copying the ZIP files to it. I then downloaded the JSON in github and modified the s3bucket references in the two code blocks. I uploaded it to AWS in us-west-2 and was able to successfully deploy the stack.

**Comment by lox** [comment]
I think this can be solved with https://aws.amazon.com/blogs/aws/new-cross-region-replication-for-amazon-s3/.

**Comment by toolmantim** [comment]
We no longer use Lambda for this, so I believe this isn't a problem anymore
