### ISSUE TITLE
Only fetches stats for 30 projects

### ISSUE THREAD

**Issue by scottharris** [buildkite/buildkite-cloudwatch-metrics-publisher#2]
We have more than 30 projects and stats collected were not complete.
The curl to https://api.buildkite.com/v1/organizations/$BUILDKITE_ORG_SLUG/projects only retrieves a max of 30 results in 1 page and then paginates.  Added ?per_page=100 to fix for now,  but should really loop over all pages to collect complete set of stats.

**Comment by toolmantim** [comment]
Thanks for the bug report! I've just pushed a fix for up to 100 projects! I've opened #3 for anyone with more than 100 projects.
